### ISSUE TITLE
Loading from a 8.4 xgapp file should not throw a NPE

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-core#23]
I get this exception:

```
java.lang.NullPointerException
gate.persist.PersistenceException: java.lang.NullPointerException
	at gate.util.persistence.PersistenceManager.loadObjectFromUrl(PersistenceManager.java:1333)
	at gate.util.persistence.PersistenceManager.loadObjectFromFile(PersistenceManager.java:1213)
	at gate.gui.MainFrame$LoadResourceFromFileAction$1.run(MainFrame.java:3697)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at gate.util.persistence.PersistenceManager$URLHolder.unpackPersistentRepresentation(PersistenceManager.java:489)
	at gate.util.persistence.PersistenceManager$URLHolder.createObject(PersistenceManager.java:461)
	at gate.util.persistence.PersistenceManager.getTransientRepresentation(PersistenceManager.java:793)
	at gate.util.persistence.CollectionPersistence.createObject(CollectionPersistence.java:82)
	at gate.util.persistence.PersistenceManager.getTransientRepresentation(PersistenceManager.java:793)
	at gate.util.persistence.PersistenceManager.getTransientRepresentation(PersistenceManager.java:774)
	at gate.util.persistence.PersistenceManager.loadObjectFromUrl(PersistenceManager.java:1286)
	... 3 more
  Caused by:
java.lang.NullPointerException
	at gate.util.persistence.PersistenceManager$URLHolder.unpackPersistentRepresentation(PersistenceManager.java:489)
	at gate.util.persistence.PersistenceManager$URLHolder.createObject(PersistenceManager.java:461)
	at gate.util.persistence.PersistenceManager.getTransientRepresentation(PersistenceManager.java:793)
	at gate.util.persistence.CollectionPersistence.createObject(CollectionPersistence.java:82)
	at gate.util.persistence.PersistenceManager.getTransientRepresentation(PersistenceManager.java:793)
	at gate.util.persistence.PersistenceManager.getTransientRepresentation(PersistenceManager.java:774)
	at gate.util.persistence.PersistenceManager.loadObjectFromUrl(PersistenceManager.java:1286)
	at gate.util.persistence.PersistenceManager.loadObjectFromFile(PersistenceManager.java:1213)
	at gate.gui.MainFrame$LoadResourceFromFileAction$1.run(MainFrame.java:3697)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by greenwoodma** [comment]
can you provide an example xgapp file as this definitely was working before

**Comment by johann-petrak** [comment]
The one where I get this is a large one that depends on other files in the directory (and produces an error, but a proper file not found error) with the old GATE version. Given that I have the file I can have a look at this myself, just added the issue as to not to forget! I will come to you with a "helpwanted" if necessary! :)

**Comment by greenwoodma** [comment]
okay cool, looks like it's something odd in the URL handling code so it could be to do with a reference to gatehome or relpath going wonky

**Comment by johann-petrak** [comment]
Yes. Gate.getGateHome() returns null now, apparently. I loaded the Groovy plugin and typed println(gate.Gate.getGateHome())  to check. 

I am not sure if this is now intended behaviour of getGateHome()? On the one hand, even if getGateHome() would return the location of GATE, the loading would not work any more since there is no plugin there, but at least we would not get an NPE but a more understandable message.

**Comment by greenwoodma** [comment]
As this caught us out again this morning I've been thinking about possible solutions.

1. we should catch uses of `$gatehome` in xgapps and print a message about it not being supported rather than simply throwing an NPE when we try and build a URL
2. the solutions are either to convert to using 8.5 plugins or load the app into 8.4 and export for GATE cloud, but how about if I log a message and then map `$gatehome` to `$relpath`? this would allow you to have a plugins folder relative to the xgapp (which is the standard) which could be easily created by hand
