### ISSUE TITLE
Starting GATE after setting stored config to LAF GTK+ fails

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-core#50]
When setting the LaF to GTK+ in GATE, then exiting GATE, then startimg again, the following exception happens and the GATE GUI never appears:
` ` ` 
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at gate.swing.ResourceReferenceChooser$Renderer.updateUI(ResourceReferenceChooser.java:711)
	at javax.swing.JLabel.<init>(JLabel.java:164)
	at javax.swing.JLabel.<init>(JLabel.java:235)
	at javax.swing.tree.DefaultTreeCellRenderer.<init>(DefaultTreeCellRenderer.java:169)
	at gate.swing.ResourceReferenceChooser$Renderer.<init>(ResourceReferenceChooser.java:680)
	at gate.swing.ResourceReferenceChooser.<init>(ResourceReferenceChooser.java:173)
	at gate.gui.MainFrame.<init>(MainFrame.java:538)
	at gate.gui.MainFrame.getInstance(MainFrame.java:366)
	at gate.Main$2.run(Main.java:186)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

` ` `

**Comment by greenwoodma** [comment]
That's nuts. Turns out that the GTK+ look and feel doesn't have an icon for tree nodes, which means we get an NPE when we try and determine the size of the icon to use in the tree.

**Comment by greenwoodma** [comment]
Strangely the GTK+ look and feel doesn't work properly on my machine (Ubuntu 16.04) but I've fixed this by assuming an icon of 16x16 if there isn't a default to work from and this seems to work well enough.
