### ISSUE TITLE
NullPointer Exception when opening serial datastore

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-core#59]
When opening a serial datastore (on a Linux machine), runnint GATE 8.6-SNAPSHOT, using Java 1.8.0_172, then double-clicking on the datastore as shown in the tree view, I get the following: (the ds was created using the same versions on the same machine):
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at gate.gui.SerialDatastoreViewer.initGuiComponents(SerialDatastoreViewer.java:237)
	at gate.gui.SerialDatastoreViewer.setTarget(SerialDatastoreViewer.java:155)
	at gate.gui.NameBearerHandle.buildViews(NameBearerHandle.java:345)
	at gate.gui.NameBearerHandle.getLargeView(NameBearerHandle.java:186)
	at gate.gui.MainFrame.select(MainFrame.java:446)
	at gate.gui.MainFrame$22.processMouseEvent(MainFrame.java:1486)
	at gate.gui.MainFrame$22.mouseClicked(MainFrame.java:1329)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.Component.processMouseEvent(Component.java:6542)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by greenwoodma** [comment]
Does the datastore still work as expected?

**Comment by johann-petrak** [comment]
OK this happens when one wants to view a datastore which contains LRs created with a plugin which is not loaded at the time of viewing. In this case it is term banks created with the TermRaider plugin.
When loading the plugin first, it works.
Maybe it is possible to detect the situation and inform the user about the LR type,  or otherwise at least handle this without throwing a null pointer exception ...

**Comment by johann-petrak** [comment]
> Does the datastore still work as expected?

No, the SerialDatastoreViewer fails and none of the other LRs can be viewed either when that happens.
