### ISSUE TITLE
Issues with http proxies

### ISSUE THREAD

**Issue by izcram** [GateNLP/gate-core#63]
I'm trying to get both GATE embedded and developer working on a machine which allows http(s) connections only via proxies, however in both cases it fails

For GATE embedded I'm doing something along the following lines

```
String host = "proxy.myorg.org";
String port = "8080";
System.setProperty("http.proxyHost", host);
System.setProperty("https.proxyHost", host);
System.setProperty("http.proxyPort", port);
System.setProperty("https.proxyPort", port);
System.setProperty("java.net.useSystemProxies", "true");
System.setProperty("http.nonProxyHosts", "localhost");
System.setProperty("https.nonProxyHosts", "localhost");

// testing whether we can reach external hosts (works fine!)
 try {
            InputStream stream = new URL("http://google.com/").openStream();
            System.out.println("REading " + stream.read());
            stream.close();
} catch (Exception e) {
            e.printStackTrace();
}

Gate.init();

Plugin plugin = new Plugin.Maven("uk.ac.gate.plugins", "stanford-corenlp", "8.5.1");
Gate.getCreoleRegister().registerPlugin(plugin);
```

This gives me: 

```
org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact uk.ac.gate.plugins:stanford-corenlp:jar:creole:8.5.1 from/to central (http://repo1.maven.org/maven2/): Connection refused (Connection refused)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:422)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:224)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:201)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:260)
	at gate.creole.Plugin$Maven.getMetadataXML(Plugin.java:740)
	at gate.creole.Plugin.parseCreole(Plugin.java:333)
	at gate.creole.Plugin.getRequiredPlugins(Plugin.java:219)
	at gate.creole.CreoleRegisterImpl.registerPlugin(CreoleRegisterImpl.java:191)
	at gate.creole.CreoleRegisterImpl.registerPlugin(CreoleRegisterImpl.java:177)
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact uk.ac.gate.plugins:stanford-corenlp:jar:creole:8.5.1 from/to central (http://repo1.maven.org/maven2/): Connection refused (Connection refused)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:52)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:365)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:583)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:259)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:498)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:399)
	... 16 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:326)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:164)
	at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:296)
	at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:252)
	at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:453)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:360)
	... 21 more
gate.util.GateException: couldn't open creole.xml for plugin: stanford-corenlp
	at gate.creole.CreoleRegisterImpl.registerPlugin(CreoleRegisterImpl.java:208)
	at gate.creole.CreoleRegisterImpl.registerPlugin(CreoleRegisterImpl.java:177)
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: xerces:xercesImpl:jar:2.8.0, joda-time:joda-time:jar:2.9: Could not transfer artifact xerces:xercesImpl:jar:2.8.0 from/to central (http://repo1.maven.org/maven2/): Connection refused (Connection refused)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:355)
	at gate.creole.Plugin$Maven.getCreoleXML(Plugin.java:855)
	at gate.creole.CreoleRegisterImpl.registerPlugin(CreoleRegisterImpl.java:196)
	... 9 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: xerces:xercesImpl:jar:2.8.0, joda-time:joda-time:jar:2.9: Could not transfer artifact xerces:xercesImpl:jar:2.8.0 from/to central (http://repo1.maven.org/maven2/): Connection refused (Connection refused)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:422)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:224)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:338)
	... 11 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact xerces:xercesImpl:jar:2.8.0 from/to central (http://repo1.maven.org/maven2/): Connection refused (Connection refused)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:52)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:365)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:326)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:164)
	at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:296)
	at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:252)
	at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:453)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:360)
```

Note, that the Maven command line is dealing fine with proxies (configured in ~/.m2/settings.xml), i.e. in order to build my code it successfully pulls the dependencies.

Could it be, that the configurations are not routed correctly through the code? Or what am I missing?

This machine is a centos 7 with Oracle java 1.8 and I'm using GATE 8.5.1

Many thanks for any hint!

**Comment by ianroberts** [comment]
Aether inside GATE is supposed to respect the same settings.xml as the maven command line uses. Can you try the same thing with the latest 8.6-SNAPSHOT, as I did make one change to the resolution logic since 8.5.1 to correctly pass through system property settings (for some reason aether doesn’t do this by default).

**Comment by izcram** [comment]
Thanks for your fast answer, much appreciated!

I've compiled GATE from source (hence 8.6-SNAPSHOT) and still no luck, i.e. the same error message. Just checking: should the plugin also be 8.6-SNAPSHOT? If so, is there a publicly available maven repository in order to test whether the mechanism works (I don't have push access to a maven repo)?

What could I try next? I'd be fine tinkering in the code as well.

**Comment by ianroberts** [comment]
All our snapshots (`gate-core` and the plugins) are published to http://repo.gate.ac.uk/content/groups/public - you should still be OK with version 8.5.1 of the plugin.

I will try to replicate this locally and do a bit of my own debugging.

**Comment by greenwoodma** [comment]
It looks as if we need to provide the proxy when we create `RemoteRepository` instances as it seems Aether (rather oddly) does nothing with proxy info by default. Not sure if the code we already have for loading the `.m2/settings.xml` pulls out the proxy info or not.

**Comment by izcram** [comment]
Small update: I could get both GATE embedded and GATE developer (8.6-SNAPSHOT) to work by tweaking the `~/.m2/settings.xml`:

```
<settings>
    <activeProfiles>
        <activeProfile>default</activeProfile>
    </activeProfiles>
    <proxies>
        <proxy>
            <id>proxy-http</id>
            <active>true</active>
            <protocol>http</protocol>
            <host>proxy.myorg.net</host>
            <port>8080</port>
        </proxy>
        <proxy>
            <id>proxy-https</id>
            <active>true</active>
            <protocol>https</protocol>
            <host>proxy.myorg.net</host>
            <port>8080</port>
        </proxy>
    </proxies>

    <profiles>
        <profile>
            <id>default</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <repositories>
                <repository>
                    <id>gaterepo</id>
                    <url>http://repo.gate.ac.uk/content/groups/public</url>
                    <snapshots>
                        <enabled>true</enabled>
                    </snapshots>
                </repository>
                <repository>
                    <id>central</id>
                    <url>https://repo1.maven.org/maven2</url>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                </repository>
            </repositories>
        </profile>
    </profiles>
</settings>
```

A crucial part was having an active profile. It would be useful though not having to rely on this settings.xml, particularly in case of GATE developer.
