### ISSUE TITLE
Odd NullPointerException after populating datastore corpus

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-core#67]
I imported a few dozen GATE documents (finf format) into a serial datastore, after this the GUI display of the language resources does not get repainted properly and every click there displays the following exception: 
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at gate.gui.MainFrame$22.processMouseEvent(MainFrame.java:1371)
	at gate.gui.MainFrame$22.mousePressed(MainFrame.java:1321)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.Component.processMouseEvent(Component.java:6536)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Java version 1.8.0_201 on Ubuntu 18.04 with GATE 8.5.1. 

Steps to reproduce:
* create a serial datastore from an empty directory
* create corpus 
* save corpus to datastore
* populate corpus 
* after the populate corpus action is completed, the language resource part of the resource tree is blank
* clicking into the blank space shows the exception above three times

**Comment by greenwoodma** [comment]
Yes it's an EDT issue and it is fixed in 8.6-SNAPSHOT -- was actually fixed less than a week after 8.5.1 was released.

**Comment by johann-petrak** [comment]
Ah sorry, I actually did try to find the corresponding issue but I failed -- which one is it?

**Comment by greenwoodma** [comment]
Not sure there was an issue, just a commit sometime around fig last year
